# Generated by Django 4.2.19 on 2025-02-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='discount_from_price',
            field=models.PositiveIntegerField(default=0, verbose_name='할인 전 가격'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='final_from_price',
            field=models.PositiveIntegerField(default=0, verbose_name='할인 후 가격'),
            preserve_default=False,
        ),
    ]
